### ISSUE TITLE
can you please support https://github.com/imaegoo/twikoo since not all visitor has an account for github.com ?

### ISSUE THREAD

**Issue by mobilelifeful** [hugomods/giscus#12]
can you please support https://github.com/imaegoo/twikoo since not all visitor has an account for github.com

**Comment by razonyang** [comment]
LGTM.

**Comment by razonyang** [comment]
Implemented, but I'm not sure if you're using the HB theme.

Docs for HB theme:

https://hbstack.dev/en/docs/modules/blog/twikoo/
https://hbstack.dev/en/docs/modules/docs/twikoo/

> You need to import the related modules and configure the `env_id`.

Docs for other modular themes:

https://hugomods.com/en/docs/comment-engines/twikoo/
